### ISSUE TITLE
Insert Filter to the Source doesn't seem to work

### ISSUE THREAD

**Issue by God-damnit-all** [norihiro/obs-async-source-duplication#8]
I'm on OBS 28.0.1 on Windows. I press the button "Insert Filter to the Source" with the proper source selected, and then I go to the source's filters, but there is no new filter there. Am I understanding the instructions correctly? Or is this just not working for OBS 28 Windows at this time?

**Comment by God-damnit-all** [comment]
The filter is available on "Asynchronous Source Duplicator" but not on the original source, I'm not sure if that's intended. The "Asynchronous Source Duplicator" source doesn't seem to produce audio, so I have to assume it isn't intended.

Also, "Asynchronous Source Duplicator" is only able to select audio sources. Based on the description on the OBS website, I don't think that's intended.

**Comment by norihiro** [comment]
Which type of the source did you try to apply the filter?

**Comment by God-damnit-all** [comment]
> Which type of the source did you try to apply the filter?

Only audio sources were in the dropdown box, except for Source Mirror. Apparently Source Mirror does work, but only partially, I couldn't get a video filter to appear for it, only the audio filter.

**Comment by norihiro** [comment]
This plugin is available for *asynchronous* sources such as AJA, Decklink, Media Source, VLC Video Source, Video Capture Device. Do you have one of these sources?

The asynchronous sources send video frame data in CPU's memory so that this plugin can grab the data. Other sources at first transfer frame data to GPU so that this plugin cannot grab the data.

When you open Filters dialog for a specific source and you cannot find Audio/Video Filters list, it's synchronous source.
Game Capture, Window Capture, and Display Capture are synchronous source and cannot be duplicated with this plugin.

**Comment by God-damnit-all** [comment]
> This plugin is available for _asynchronous_ sources such as AJA, Decklink, Media Source, VLC Video Source, Video Capture Device. Do you have one of these sources?
> 
> The asynchronous sources send video frame data in CPU's memory so that this plugin can grab the data. Other sources at first transfer frame data to GPU so that this plugin cannot grab the data.
> 
> When you open Filters dialog for a specific source and you cannot find Audio/Video Filters list, it's synchronous source. Game Capture, Window Capture, and Display Capture are synchronous source and cannot be duplicated with this plugin.

I thought it was a tool to make sources that were normally synchronous into asynchronous ones, my bad.
